// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJMGUI6XAiOx_f1goQdJZJNMynCPwGeIs',
    appId: '1:855710915094:web:7a4dc7d278cc2487a13337',
    messagingSenderId: '855710915094',
    projectId: 'safety-sos-app-4ab3c',
    authDomain: 'safety-sos-app-4ab3c.firebaseapp.com',
    storageBucket: 'safety-sos-app-4ab3c.firebasestorage.app',
    measurementId: 'G-VCJTGB2QTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEcvKf9fF_hHHNFE6IJVZWFIJaIR-frc4',
    appId: '1:855710915094:android:c72deb76605b6f6ba13337',
    messagingSenderId: '855710915094',
    projectId: 'safety-sos-app-4ab3c',
    storageBucket: 'safety-sos-app-4ab3c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHRbpX61ESyLnJA9yxgGoip2bR8HR8ba8',
    appId: '1:855710915094:ios:9330ca5950eabb59a13337',
    messagingSenderId: '855710915094',
    projectId: 'safety-sos-app-4ab3c',
    storageBucket: 'safety-sos-app-4ab3c.firebasestorage.app',
    iosBundleId: 'com.example.alertmate2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHRbpX61ESyLnJA9yxgGoip2bR8HR8ba8',
    appId: '1:855710915094:ios:9330ca5950eabb59a13337',
    messagingSenderId: '855710915094',
    projectId: 'safety-sos-app-4ab3c',
    storageBucket: 'safety-sos-app-4ab3c.firebasestorage.app',
    iosBundleId: 'com.example.alertmate2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJMGUI6XAiOx_f1goQdJZJNMynCPwGeIs',
    appId: '1:855710915094:web:7a4dc7d278cc2487a13337',
    messagingSenderId: '855710915094',
    projectId: 'safety-sos-app-4ab3c',
    authDomain: 'safety-sos-app-4ab3c.firebaseapp.com',
    storageBucket: 'safety-sos-app-4ab3c.firebasestorage.app',
    measurementId: 'G-VCJTGB2QTW',
  );

}